# Generated by Django 3.2.13 on 2022-06-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('major', models.CharField(default='교양', max_length=15)),
                ('credit', models.IntegerField(default=2, null=True)),
                ('name', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.CharField(max_length=20, null=True)),
                ('class_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='22-1 semester', max_length=15)),
                ('assignment', models.CharField(max_length=10)),
                ('groupmeeting', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=15)),
                ('attendence', models.CharField(max_length=15)),
                ('numberoftests', models.CharField(max_length=15)),
                ('body', models.TextField(default='내용')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.class')),
            ],
        ),
    ]
