# Generated by Django 3.2.13 on 2022-06-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
