# Generated by Django 3.2.13 on 2022-06-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_class_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
