# Generated by Django 3.2.13 on 2022-06-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_review_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assignment',
            field=models.CharField(choices=[('1', 'Many'), ('2', 'Normal'), ('3', 'None')], default='3', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='attendence',
            field=models.CharField(choices=[('1', 'Mixed'), ('2', 'Direct name'), ('3', 'Designated seat'), ('4', 'Electronic attendence')], default='1', max_length=21),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(default='Please write a general review of this lecture'),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[('1', 'Genorosity'), ('2', 'Mediocrity'), ('3', 'Strictness')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='groupmeeting',
            field=models.CharField(choices=[('1', 'Many'), ('2', 'Normal'), ('3', 'None')], default='3', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='numberoftests',
            field=models.CharField(choices=[('1', '0'), ('2', '1'), ('3', '2'), ('4', '3'), ('5', '4+')], default='1', max_length=2),
        ),
    ]
