# Generated by Django 3.2.13 on 2022-06-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20220629_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
