# Generated by Django 3.2.13 on 2022-06-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_class_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='credit',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='classroom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
