# Generated by Django 3.2.13 on 2022-06-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20220624_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='major',
            field=models.CharField(default='교양', max_length=15),
        ),
    ]
