# Generated by Django 3.2.13 on 2022-06-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_class_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='22-1 semester', max_length=15)),
                ('assignment', models.CharField(max_length=10)),
                ('groupmeeting', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=15)),
                ('attendence', models.CharField(max_length=15)),
                ('numberoftests', models.CharField(max_length=15)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.class')),
            ],
        ),
    ]
